# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://github.com/pre-commit/pre-commit-hooks
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, "lf"]
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb, "50000"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "govern",
            "agent",
            "build",
            "chore",
            "ci",
            "docs",
            "dx",
            "feat",
            "perf",
            "refactor",
            "revert",
            "style",
            "test",
            "fix",
          ]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.2.0
    hooks:
      - id: editorconfig-checker
        stages:
          - pre-commit

  - repo: https://github.com/crate-ci/typos
    rev: v1.35.1
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: swift-format
        stages: [pre-commit]
        name: swift-format
        language: system
        entry: bun
        args: ["fmt:swift"]
        files: \.swift$

  - repo: local
    hooks:
      - id: fmt
        stages: [pre-commit]
        name: Run bun fmt
        language: system
        entry: bun
        args: ["fmt:docs"]
