[default]
extend-ignore-re = [
  # typos: ignore
  "(?Rm)^.*(#|///?)\\s*typos: ?ignore$",

  # typos: <on|off>
  "(?s)(#|///?)\\s*typos: ?off.*?\\n\\s*(#|///?)\\s*typos: ?on",

  # typos: ignore-next
  "(#|///?)\\s*typos: ?ignore-next\\n.*",
]

extend-ignore-identifiers-re = [
  # At least 3 letters
  "^[0-9A-Za-z]{0,2}$",
]

extend-ignore-words-re = [
  # At least 3 letters
  "^[0-9A-Za-z]{0,2}$",
]

[default.extend-words]
aesthetic = "æsthetic"
reexamining = "reëxamining"
re-examining = "reëxamining"

[default.extend-identifiers]

[files]
extend-exclude = [
  "typos.toml"
]
