#!/bin/bash
#
#  SPDX-License-Identifier: MIT
#  Copyright (c) 2026 Paal Øye-Strømme
#
#  generate_build_info.sh
#  Rukzak
#
#  Generates a build configuration file with Git metadata
#

set -euo pipefail

# Use SRCROOT provided by Xcode or default to current directory
ROOT_DIR="${SRCROOT:-.}"
OUTPUT_FILE="${ROOT_DIR}/Config/GeneratedBuildInfo.xcconfig"

# Ensure Config directory exists
mkdir -p "${ROOT_DIR}/Config"

# It's here for Git to resolve .git directory
cd "${ROOT_DIR}"

# Get current Git commit hash
GIT_COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BUILD_STATUS="clean"

# Check if working directory is dirty (modified tracked files)
if ! git diff-index --quiet HEAD -- 2>/dev/null; then
    GIT_BUILD_STATUS="dirty"
fi

# Check for untracked files
if [ -n "$(git ls-files --others --exclude-standard 2>/dev/null)" ]; then
    GIT_BUILD_STATUS="dirty"
fi

# Override status in CI environments
if [ "${CI:-}" = "true" ] || [ -n "${GITHUB_ACTIONS:-}" ]; then
    GIT_BUILD_STATUS="clean"
fi

# Write to xcconfig file
cat > "${OUTPUT_FILE}" << EOF
// Generated by generate_build_info.sh
GIT_COMMIT_HASH = ${GIT_COMMIT_HASH}
GIT_BUILD_STATUS = ${GIT_BUILD_STATUS}
EOF

echo "Generated ${OUTPUT_FILE}: hash=${GIT_COMMIT_HASH}, status=${GIT_BUILD_STATUS}"
